// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0_nx5xz-0MG9H7ndCnEJqbH4SsHJhwWk',
    appId: '1:497614345243:web:2196095a70659b459dd4be',
    messagingSenderId: '497614345243',
    projectId: 'burclar-d8a0b',
    authDomain: 'burclar-d8a0b.firebaseapp.com',
    storageBucket: 'burclar-d8a0b.appspot.com',
    measurementId: 'G-FZ0XMP598N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ476o9dJbnliNWfmAxEauNU7ljstvnwk',
    appId: '1:497614345243:android:57a4636134a7d4839dd4be',
    messagingSenderId: '497614345243',
    projectId: 'burclar-d8a0b',
    storageBucket: 'burclar-d8a0b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYSlg9FkQQfk1RHSnRosaSikTGwbYoGAk',
    appId: '1:497614345243:ios:f55772505b8bfd509dd4be',
    messagingSenderId: '497614345243',
    projectId: 'burclar-d8a0b',
    storageBucket: 'burclar-d8a0b.appspot.com',
    iosClientId: '497614345243-0bjed8eg1o1tpq950c6n40vso6unoe6r.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYSlg9FkQQfk1RHSnRosaSikTGwbYoGAk',
    appId: '1:497614345243:ios:f55772505b8bfd509dd4be',
    messagingSenderId: '497614345243',
    projectId: 'burclar-d8a0b',
    storageBucket: 'burclar-d8a0b.appspot.com',
    iosClientId: '497614345243-0bjed8eg1o1tpq950c6n40vso6unoe6r.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
